const MASTER_DATA = [
  {
    "process": "INBOUND",
    "activity": "Receiving",
    "element": "Menerima barang dari supplier/vendor",
    "classification": "Direct Value-Added",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 40.0,
    "notes": "Contoh - tinjau ulang sesuai proses aktual"
  },
  {
    "process": "INBOUND",
    "activity": "Receiving",
    "element": "Memeriksa dokumen/manifest penerimaan",
    "classification": "Indirect",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 40.0,
    "notes": "Contoh - tinjau ulang sesuai proses aktual"
  },
  {
    "process": "INBOUND",
    "activity": "Receiving",
    "element": "Memeriksa quantity barang",
    "classification": "Direct Value-Added",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 40.0,
    "notes": "Contoh - tinjau ulang sesuai proses aktual"
  },
  {
    "process": "INBOUND",
    "activity": "Receiving",
    "element": "Memeriksa kondisi barang/packing",
    "classification": "Non-Value-Added",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 40.0,
    "notes": "Contoh - tinjau ulang sesuai proses aktual"
  },
  {
    "process": "INBOUND",
    "activity": "Receiving",
    "element": "Melakukan scanning/input penerimaan",
    "classification": "Indirect",
    "waste": "-",
    "method": "Alat Bantu",
    "equipment": "PDT",
    "frequency": 40.0,
    "notes": "Contoh - tinjau ulang sesuai proses aktual"
  },
  {
    "process": "INBOUND",
    "activity": "Receiving",
    "element": "Memindahkan barang ke area receiving/staging",
    "classification": "Direct Value-Added",
    "waste": "-",
    "method": "Mesin",
    "equipment": "Conveyor",
    "frequency": 40.0,
    "notes": "Contoh - tinjau ulang sesuai proses aktual"
  },
  {
    "process": "INBOUND",
    "activity": "Receiving",
    "element": "Menempatkan barang untuk proses selanjutnya",
    "classification": "Direct Value-Added",
    "waste": "-",
    "method": "Alat Bantu",
    "equipment": "Trolley",
    "frequency": 40.0,
    "notes": "Contoh - tinjau ulang sesuai proses aktual"
  },
  {
    "process": "INBOUND",
    "activity": "QI/QC",
    "element": "Menerima barang untuk pemeriksaan",
    "classification": "Indirect",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 40.0,
    "notes": "Contoh - tinjau ulang sesuai proses aktual"
  },
  {
    "process": "INBOUND",
    "activity": "QI/QC",
    "element": "Menyiapkan barang untuk inspection",
    "classification": "Direct Value-Added",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 40.0,
    "notes": "Contoh - tinjau ulang sesuai proses aktual"
  },
  {
    "process": "INBOUND",
    "activity": "QI/QC",
    "element": "Memeriksa quantity dan part number",
    "classification": "Direct Value-Added",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 40.0,
    "notes": "Contoh - tinjau ulang sesuai proses aktual"
  },
  {
    "process": "INBOUND",
    "activity": "QI/QC",
    "element": "Melakukan pemeriksaan kondisi/kualitas barang",
    "classification": "Direct Value-Added",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 40.0,
    "notes": "Contoh - tinjau ulang sesuai proses aktual"
  },
  {
    "process": "INBOUND",
    "activity": "QI/QC",
    "element": "Mencatat hasil pemeriksaan",
    "classification": "Indirect",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 40.0,
    "notes": "Contoh - tinjau ulang sesuai proses aktual"
  },
  {
    "process": "INBOUND",
    "activity": "QI/QC",
    "element": "Memberikan status/label hasil inspection",
    "classification": "Direct Value-Added",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 120.0,
    "notes": "Contoh - tinjau ulang sesuai proses aktual"
  },
  {
    "process": "INBOUND",
    "activity": "QI/QC",
    "element": "Memindahkan barang ke area proses berikutnya",
    "classification": "Direct Value-Added",
    "waste": "-",
    "method": "Alat Bantu",
    "equipment": "Trolley",
    "frequency": 120.0,
    "notes": "Contoh - tinjau ulang sesuai proses aktual"
  },
  {
    "process": "STORAGE",
    "activity": "Binning",
    "element": "Menerima barang untuk proses binning",
    "classification": "Indirect",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 120.0,
    "notes": "Contoh - tinjau ulang sesuai proses aktual"
  },
  {
    "process": "STORAGE",
    "activity": "Binning",
    "element": "Mengidentifikasi part dan lokasi bin",
    "classification": "Direct Value-Added",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "STORAGE",
    "activity": "Binning",
    "element": "Menuju lokasi bin",
    "classification": "Direct Value-Added",
    "waste": "-",
    "method": "Alat Bantu",
    "equipment": "Trolley",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "STORAGE",
    "activity": "Binning",
    "element": "Menempatkan barang ke bin",
    "classification": "Direct Value-Added",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "STORAGE",
    "activity": "Binning",
    "element": "Melakukan scanning/update lokasi",
    "classification": "Indirect",
    "waste": "-",
    "method": "Alat Bantu",
    "equipment": "PDT",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "STORAGE",
    "activity": "Binning",
    "element": "Memastikan kesesuaian barang dan lokasi",
    "classification": "Direct Value-Added",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "OUTBOUND",
    "activity": "Picking",
    "element": "Menerima picking order/task",
    "classification": "Indirect",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "OUTBOUND",
    "activity": "Picking",
    "element": "Mengidentifikasi part dan lokasi",
    "classification": "Direct Value-Added",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "OUTBOUND",
    "activity": "Picking",
    "element": "Menuju lokasi part",
    "classification": "Direct Value-Added",
    "waste": "-",
    "method": "Alat Bantu",
    "equipment": "Trolley",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "OUTBOUND",
    "activity": "Picking",
    "element": "Mengambil part sesuai quantity",
    "classification": "Direct Value-Added",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "OUTBOUND",
    "activity": "Picking",
    "element": "Melakukan scanning/verifikasi part",
    "classification": "Indirect",
    "waste": "-",
    "method": "Alat Bantu",
    "equipment": "PDT",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "OUTBOUND",
    "activity": "Picking",
    "element": "Menempatkan part ke trolley/container",
    "classification": "Direct Value-Added",
    "waste": "-",
    "method": "Alat Bantu",
    "equipment": "Trolley",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "OUTBOUND",
    "activity": "Picking",
    "element": "Membawa hasil picking ke area staging",
    "classification": "Direct Value-Added",
    "waste": "-",
    "method": "Alat Bantu",
    "equipment": "Hand Pallet",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "OUTBOUND",
    "activity": "Shipping",
    "element": "Menerima barang/order untuk shipment",
    "classification": "Indirect",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "OUTBOUND",
    "activity": "Shipping",
    "element": "Memeriksa kesesuaian barang dan dokumen",
    "classification": "Indirect",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "OUTBOUND",
    "activity": "Shipping",
    "element": "Menyiapkan barang untuk shipment",
    "classification": "Direct Value-Added",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "OUTBOUND",
    "activity": "Shipping",
    "element": "Memindahkan barang ke area shipping",
    "classification": "Direct Value-Added",
    "waste": "-",
    "method": "Mesin",
    "equipment": "Forklift",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "OUTBOUND",
    "activity": "Shipping",
    "element": "Melakukan pengecekan akhir sebelum pengiriman",
    "classification": "Direct Value-Added",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "OUTBOUND",
    "activity": "Shipping",
    "element": "Menyerahkan barang untuk proses pengiriman",
    "classification": "Direct Value-Added",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "OUTBOUND",
    "activity": "Delivery Schedule",
    "element": "Menerima/meninjau delivery request",
    "classification": "Indirect",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "OUTBOUND",
    "activity": "Delivery Schedule",
    "element": "Memeriksa detail dan kebutuhan delivery",
    "classification": "Indirect",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "OUTBOUND",
    "activity": "Delivery Schedule",
    "element": "Menentukan/menyesuaikan jadwal delivery",
    "classification": "Indirect",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "OUTBOUND",
    "activity": "Delivery Schedule",
    "element": "Mengalokasikan barang/order sesuai jadwal",
    "classification": "Indirect",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "OUTBOUND",
    "activity": "Delivery Schedule",
    "element": "Menginput/update delivery schedule",
    "classification": "Indirect",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "OUTBOUND",
    "activity": "Delivery Schedule",
    "element": "Menginformasikan jadwal delivery",
    "classification": "Indirect",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "OUTBOUND",
    "activity": "Order Processing",
    "element": "Menerima order",
    "classification": "Indirect",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "OUTBOUND",
    "activity": "Order Processing",
    "element": "Memeriksa detail order",
    "classification": "Indirect",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "OUTBOUND",
    "activity": "Order Processing",
    "element": "Memverifikasi part number dan quantity",
    "classification": "Indirect",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "OUTBOUND",
    "activity": "Order Processing",
    "element": "Memeriksa ketersediaan stock",
    "classification": "Indirect",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "OUTBOUND",
    "activity": "Order Processing",
    "element": "Menginput/memproses order ke sistem",
    "classification": "Indirect",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "OUTBOUND",
    "activity": "Order Processing",
    "element": "Meneruskan order ke proses berikutnya",
    "classification": "Indirect",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "OUTBOUND",
    "activity": "PST",
    "element": "Menerima request PST",
    "classification": "Indirect",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "OUTBOUND",
    "activity": "PST",
    "element": "Memeriksa detail request",
    "classification": "Indirect",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "OUTBOUND",
    "activity": "PST",
    "element": "Memeriksa ketersediaan part",
    "classification": "Indirect",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "OUTBOUND",
    "activity": "PST",
    "element": "Menyiapkan/mengambil part",
    "classification": "Direct Value-Added",
    "waste": "-",
    "method": "Alat Bantu",
    "equipment": "Trolley",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "OUTBOUND",
    "activity": "PST",
    "element": "Melakukan verifikasi part dan quantity",
    "classification": "Direct Value-Added",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "OUTBOUND",
    "activity": "PST",
    "element": "Menyerahkan/memproses PST",
    "classification": "Direct Value-Added",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 0.0,
    "notes": ""
  },
  {
    "process": "OUTBOUND",
    "activity": "PST",
    "element": "Mengupdate status PST",
    "classification": "Indirect",
    "waste": "-",
    "method": "Manual",
    "equipment": "-",
    "frequency": 0.0,
    "notes": ""
  }
];
const OPERATORS = ["Soleh", "Topan", "Ale", "Moko", "Budi", "Sari", "Andi"];
